### PR TITLE
Make the library compile with agda 2.5.4.2 & stdlib-0.16. NaturalTransformation need more attention.

### PR DESCRIPTION
**Pull request by p-pavel**

### CODE REVIEW

**Comment by p-pavel** [comment]
I'll be glad if anybody could remove the ugliness in NaturalTransformation and Power/NaturalTransformation 

the need for eta-equality in virtually any record seem to be a bug in 2.5.4.2

**Comment by p-pavel** [comment]
closed accidentally

**Review by JacquesCarette — DISMISSED** [review]
Sorry to take so long to review this.  Looks great! Just the one minor thing, and I'll merge it.

**Comment by JacquesCarette** [comment]
Would you be able to extract out a small example of the regression that requires `eta-equality`?  I've encountered that too, but wasn't able to come up with a small example.

**Comment by JacquesCarette** [comment]
Note that this does NOT work under stdlib-1.0. It looks like things with irrelevance have completely broken this library.

**Comment by HuStmpHrrr** [comment]
like by how much? is it worth fixing or better start another category theory library from scratch, potentially taking advantages of 2.6?

**Comment by JacquesCarette** [comment]
Super broken - I encounter hard errors from Agda, a la
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:289
```
on quite a few files.  I think "from scratch" is now the way to go.

**Pull request merged**
